# Generated by Django 5.0.3 on 2024-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс новости')),
                ('full_text', models.TextField(verbose_name='Полный текст новости')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
