# Generated by Django 5.0.3 on 2024-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_arts_article_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
