# Generated by Django 5.0.3 on 2024-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/img/', verbose_name='Изображение'),
        ),
    ]
