# Generated by Django 5.0.3 on 2024-04-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='relevance',
            field=models.BooleanField(default='True', verbose_name='Актуальность'),
        ),
    ]
