# Generated by Django 5.0.3 on 2024-04-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competitions_relevance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitions',
            name='relevance',
        ),
    ]
