# Generated by Django 5.0.6 on 2024-05-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_test_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='competitions.test')),
            ],
        ),
    ]
