# Generated by Django 5.0.3 on 2024-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='uploads/submissions/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/task_images/', verbose_name='Изображение задания'),
        ),
    ]
