# Generated by Django 5.0.3 on 2024-06-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_submission_file_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.task'),
        ),
    ]
