# Generated by Django 5.0.3 on 2024-06-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_submission_grade'),
        ('users', '0004_studenttoteacher_competition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoteacher',
            name='competition_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='competitions.competitions'),
        ),
    ]
