# Generated by Django 5.0.3 on 2024-06-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_submission_file_alter_task_image'),
        ('users', '0005_alter_studenttoteacher_competition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoteacher',
            name='competition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='competitions.competitions'),
        ),
    ]
